package tests

import (
	"net/http"
	"strings"
	"testing"

	"github.com/zhenjb/ganc-sys/pkg/types"
)

func TestINT07BuildBatchCallsBuilderWithIndexedDepositsAndPersistedWithdrawRequests(t *testing.T) {
	server := newTestServer()

	depositResp := createDepositForTest(t, server, "100")
	withdrawResp := createWithdrawRequestForTest(t, server, "40")

	buildReq := types.BuildBatchRequestBody{
		DepositIDs:  []string{depositResp.DepositRecord.DepositID},
		WithdrawIDs: []string{withdrawResp.WithdrawRequest.WithdrawID},
	}

	buildRec := performRequest(t, server, http.MethodPost, "/api/batch/build", buildReq)
	if buildRec.Code != http.StatusOK {
		t.Fatalf("expected build batch status 200, got %d, body=%s", buildRec.Code, buildRec.Body.String())
	}

	body := decodeJSON[types.BuildBatchResponse](t, buildRec)

	if body.SettlementUpdate.BatchID == "" {
		t.Fatalf("expected batchId to be generated by builder")
	}

	if body.SettlementUpdate.OldStateRoot != "0xrootA" {
		t.Fatalf("expected oldStateRoot=0xrootA, got %q", body.SettlementUpdate.OldStateRoot)
	}

	if body.SettlementUpdate.NewStateRoot == "" {
		t.Fatalf("expected newStateRoot to be generated by builder")
	}

	if len(body.SettlementUpdate.Deposits) != 1 {
		t.Fatalf("expected 1 deposit, got %d", len(body.SettlementUpdate.Deposits))
	}

	if body.SettlementUpdate.Deposits[0].Amount != "100" {
		t.Fatalf("expected deposit amount=100, got %q", body.SettlementUpdate.Deposits[0].Amount)
	}

	if len(body.SettlementUpdate.Withdrawals) != 1 {
		t.Fatalf("expected 1 withdrawal, got %d", len(body.SettlementUpdate.Withdrawals))
	}

	withdrawal := body.SettlementUpdate.Withdrawals[0]

	if withdrawal.Amount != "40" {
		t.Fatalf("expected withdrawal amount=40, got %q", withdrawal.Amount)
	}

	if !strings.HasPrefix(withdrawal.DestinationHash, "0x") {
		t.Fatalf("expected destinationHash to start with 0x, got %q", withdrawal.DestinationHash)
	}

	if !strings.HasPrefix(withdrawal.Nullifier, "0x") {
		t.Fatalf("expected nullifier to start with 0x, got %q", withdrawal.Nullifier)
	}

	if withdrawal.DestinationHash == "0xmockdestinationhash" {
		t.Fatalf("expected builder-computed destinationHash, got placeholder")
	}

	if withdrawal.Nullifier == "0xmocknullifier" {
		t.Fatalf("expected builder-computed nullifier, got placeholder")
	}

	if body.BatchCommitments.DepositsRoot == "" {
		t.Fatalf("expected depositsRoot to be generated by builder")
	}

	if body.BatchCommitments.DepositsRoot == "0xdepositsRoot" {
		t.Fatalf("expected builder-computed depositsRoot, got placeholder")
	}

	if body.BatchCommitments.WithdrawalsRoot == "0xwithdrawalsRoot" {
		t.Fatalf("expected builder-computed withdrawalsRoot, got placeholder")
	}

	if body.BatchCommitments.NullifiersRoot == "0xnullifiersRoot" {
		t.Fatalf("expected builder-computed nullifiersRoot, got placeholder")
	}

	if body.BatchCommitments.WithdrawOutputsRoot == "0xwithdrawOutputsRoot" {
		t.Fatalf("expected builder-computed withdrawOutputsRoot, got placeholder")
	}

	if len(body.Witness.Accounts) != 1 {
		t.Fatalf("expected 1 witness account, got %d", len(body.Witness.Accounts))
	}

	account := body.Witness.Accounts[0]

	if account.Owner != "cosmos1alice" {
		t.Fatalf("expected witness owner=cosmos1alice, got %q", account.Owner)
	}

	if account.OldBalance != "0" {
		t.Fatalf("expected oldBalance=0, got %q", account.OldBalance)
	}

	if account.NewBalance != "60" {
		t.Fatalf("expected newBalance=60, got %q", account.NewBalance)
	}

	if account.Nonce != "1" {
		t.Fatalf("expected nonce=1, got %q", account.Nonce)
	}

	if body.State.BatchStatus != "built" {
		t.Fatalf("expected batchStatus=built, got %q", body.State.BatchStatus)
	}

	if body.State.WithdrawStatus != "batchBuilt" {
		t.Fatalf("expected withdrawStatus=batchBuilt, got %q", body.State.WithdrawStatus)
	}
}

func TestINT07BuildBatchRejectsInsufficientOffchainBalance(t *testing.T) {
	server := newTestServer()

	depositResp := createDepositForTest(t, server, "30")
	withdrawResp := createWithdrawRequestForTest(t, server, "40")

	buildReq := types.BuildBatchRequestBody{
		DepositIDs:  []string{depositResp.DepositRecord.DepositID},
		WithdrawIDs: []string{withdrawResp.WithdrawRequest.WithdrawID},
	}

	buildRec := performRequest(t, server, http.MethodPost, "/api/batch/build", buildReq)
	if buildRec.Code != http.StatusBadRequest {
		t.Fatalf("expected build batch status 400, got %d, body=%s", buildRec.Code, buildRec.Body.String())
	}

	body := decodeJSON[map[string]string](t, buildRec)

	if body["error"] != "insufficient off-chain balance" {
		t.Fatalf("expected insufficient off-chain balance error, got %q", body["error"])
	}
}

func TestINT07BuildBatchRejectsUnknownDeposit(t *testing.T) {
	server := newTestServer()

	withdrawResp := createWithdrawRequestForTest(t, server, "40")

	buildReq := types.BuildBatchRequestBody{
		DepositIDs:  []string{"unknown"},
		WithdrawIDs: []string{withdrawResp.WithdrawRequest.WithdrawID},
	}

	buildRec := performRequest(t, server, http.MethodPost, "/api/batch/build", buildReq)
	if buildRec.Code != http.StatusNotFound {
		t.Fatalf("expected build batch status 404, got %d, body=%s", buildRec.Code, buildRec.Body.String())
	}

	body := decodeJSON[map[string]string](t, buildRec)

	if body["error"] != "deposit not found" {
		t.Fatalf("expected deposit not found error, got %q", body["error"])
	}
}

func TestINT07BuildBatchRejectsUnknownWithdrawRequest(t *testing.T) {
	server := newTestServer()

	depositResp := createDepositForTest(t, server, "100")

	buildReq := types.BuildBatchRequestBody{
		DepositIDs:  []string{depositResp.DepositRecord.DepositID},
		WithdrawIDs: []string{"unknown"},
	}

	buildRec := performRequest(t, server, http.MethodPost, "/api/batch/build", buildReq)
	if buildRec.Code != http.StatusNotFound {
		t.Fatalf("expected build batch status 404, got %d, body=%s", buildRec.Code, buildRec.Body.String())
	}

	body := decodeJSON[map[string]string](t, buildRec)

	if body["error"] != "withdraw request not found" {
		t.Fatalf("expected withdraw request not found error, got %q", body["error"])
	}
}

func createDepositForTest(t *testing.T, server http.Handler, amount string) types.DepositResponse {
	t.Helper()

	req := types.DepositRequestBody{
		Owner:  "cosmos1alice",
		Denom:  "uusdc",
		Amount: amount,
	}

	rec := performRequest(t, server, http.MethodPost, "/api/deposit", req)
	if rec.Code != http.StatusOK {
		t.Fatalf("expected deposit status 200, got %d, body=%s", rec.Code, rec.Body.String())
	}

	return decodeJSON[types.DepositResponse](t, rec)
}

func createWithdrawRequestForTest(t *testing.T, server http.Handler, amount string) types.WithdrawRequestResponse {
	t.Helper()

	req := types.WithdrawRequestBody{
		Owner:       "cosmos1alice",
		Denom:       "uusdc",
		Amount:      amount,
		Destination: "cosmos1alice",
	}

	rec := performRequest(t, server, http.MethodPost, "/api/withdraw-request", req)
	if rec.Code != http.StatusOK {
		t.Fatalf("expected withdraw request status 200, got %d, body=%s", rec.Code, rec.Body.String())
	}

	return decodeJSON[types.WithdrawRequestResponse](t, rec)
}
